<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('qdb')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_qdb.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('qdb.so')) return;
    } else {
      if (!dl('qdb.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class qdb {
	const qdb_e_ok = 0;

	const qdb_e_system = 1;

	const qdb_e_internal = 2;

	const qdb_e_no_memory = 3;

	const qdb_e_invalid_protocol = 4;

	const qdb_e_host_not_found = 5;

	const qdb_e_invalid_option = 6;

	const qdb_e_alias_too_long = 7;

	const qdb_e_alias_not_found = 8;

	const qdb_e_alias_already_exists = 9;

	const qdb_e_timeout = 10;

	const qdb_e_buffer_too_small = 11;

	const qdb_e_invalid_command = 12;

	const qdb_e_invalid_input = 13;

	const qdb_e_connection_refused = 14;

	const qdb_e_connection_reset = 15;

	const qdb_e_unexpected_reply = 16;

	const qdb_e_not_implemented = 17;

	const qdb_e_unstable_hive = 18;

	const qdb_e_protocol_error = 19;

	const qdb_e_outdated_topology = 20;

	const qdb_e_wrong_peer = 21;

	const qdb_e_invalid_version = 22;

	const qdb_e_try_again = 23;

	const qdb_e_invalid_argument = 24;

	const qdb_e_out_of_bounds = 25;

	const qdb_e_conflict = 26;

	const qdb_e_not_connected = 27;

	const qdb_o_log_function = 0;

	const qdb_o_log_context = qdb_o_log_context;

	const qdb_o_operation_timeout = qdb_o_operation_timeout;

	static function qdb_open_tcp() {
		return qdb_open_tcp();
	}

	static function qdb_close($handle) {
		return qdb_close($handle);
	}

	static function qdb_connect($handle,$host,$port) {
		return qdb_connect($handle,$host,$port);
	}

	static function qdb_get_buffer($handle,$REF,$REF_,$REF__) {
		return qdb_get_buffer($handle,$REF,$REF_,$REF__);
	}

	static function qdb_put($handle,$REF,$REF_,$content_length) {
		return qdb_put($handle,$REF,$REF_,$content_length);
	}

	static function qdb_update($handle,$REF,$REF_,$content_length) {
		return qdb_update($handle,$REF,$REF_,$content_length);
	}

	static function qdb_remove($handle,$REF) {
		return qdb_remove($handle,$REF);
	}

	static function qdb_remove_all($handle) {
		return qdb_remove_all($handle);
	}
}

/* PHP Proxy Classes */

?>
